### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by 0x416c69** [staaky/tipped#1]
Hi.

Thank you for this library.

I wonder if this is PRO or not? Is there any support? Your forums are shut down.

**Comment by DeysonOrtiz** [comment]
I just noticed that as well.  It seems the Vimeo JSON examples on the site are not working.

**Comment by staaky** [comment]
Yes, the Pro version has been open sourced and is free now. That’s what this is, there’s no more light version.

I’ll have to look into issues with the site/forum, it’s probably related to a migration, thanks.
